// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // The Prisma CLI (migrate/generate) needs a DIRECT, non-pooled connection.
    // Neon's pooler (PgBouncer) can't hold the session-level advisory lock that
    // `migrate deploy` acquires, which causes P1002 timeouts during the build.
    // The runtime client (src/lib/db.ts) still uses the pooled DATABASE_URL.
    // DIRECT_URL is the same connection string with "-pooler" removed from host.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
